export let COMMON_COURTS_KYIV = 'https://docs.google.com/spreadsheets/d/13QGQ7SF3zJ7cO-COBGIF4TgECG6NR_NYD9VwQOkm4Go/edit?usp=sharing';
export let COMMON_COURTS_VINNYTSKA = 'https://docs.google.com/spreadsheets/d/1JGJzri1gLLyKQKED3RuXZEhJ9L4Yz_rDhpc0y-xH14c/edit?usp=sharing';
export let COMMON_COURTS_VOLYNSKA = 'https://docs.google.com/spreadsheets/d/1zTuHQKGVOuvUg8BWC_GZSq0cKD4LXSRQZnphN-g2PYU/edit?usp=sharing';
export let COMMON_COURTS_DNIPROPETROVSKA = 'https://docs.google.com/spreadsheets/d/1_KjFQeMaQPZ2MTbz3UrCWeApoEVaAC_qUfofJULIvD4/edit?usp=sharing';
export let COMMON_COURTS_DONETSKA = 'https://docs.google.com/spreadsheets/d/1QndR-Ch0oUFKNRBI4_NzENe-v-8e_iJ7-Vr_U4S7hII/edit?usp=sharing';
export let COMMON_COURTS_ZHYTOMYRSKA = 'https://docs.google.com/spreadsheets/d/1Soxh4HF9IBls5gCEaFpwa-Ma0po_tk5MYKCCd8gR3d0/edit?usp=sharing';
export let COMMON_COURTS_ZAKARPATSKA = 'https://docs.google.com/spreadsheets/d/1vepQYLKYYtKk_39Unow7MJf2QRnNJgrB4So2NRW8SFI/edit?usp=sharing';
export let COMMON_COURTS_ZAPORIZHZKA = 'https://docs.google.com/spreadsheets/d/14BngXzC0g9NoZVIvr2JtzZScTaOCeFQurCaYgxJPn-M/edit?usp=sharing';
export let COMMON_COURTS_IVANO_FRANKIVSKA = 'https://docs.google.com/spreadsheets/d/1C6UtJ9KPpzbKJhqKHKYSFcN08AlCLagZp0XyZYRT8Nc/edit?usp=sharing';
export let COMMON_COURTS_KYIVSKA = 'https://docs.google.com/spreadsheets/d/1kukQSM1rMkcQhzHWo6_JtiUXX8FrDZQqcc_MjfAKO1g/edit?usp=sharing';
export let COMMON_COURTS_KIROVOGRADSKA = 'https://docs.google.com/spreadsheets/d/1VQDeHQ8R7Af0Me5oMPEAJ20VYGbYXJYUmZI_vQpXRq8/edit?usp=sharing';
export let COMMON_COURTS_LUHANSKA = 'https://docs.google.com/spreadsheets/d/1fihrC8o_buP9Ga5DUZ7JEVM9Qn-nw6UfzFIBC-zDI1w/edit?usp=sharing';
export let COMMON_COURTS_LVIVSKA = 'https://docs.google.com/spreadsheets/d/1HX0v-hQyJsix7o-W7ga8_rk2grW_NtJnuYlrgFXvUYQ/edit?usp=sharing';
export let COMMON_COURTS_MYKOLAIVSKA = 'https://docs.google.com/spreadsheets/d/1hHyA3m8C3AHhMLdSi7bRzD8cP24KU7Ot82I57ow4NFE/edit?usp=sharing';
export let COMMON_COURTS_ODESKA = 'https://docs.google.com/spreadsheets/d/13mRG3_mwHkaKxvrBah9dTYLptlhpoqu_BfCJFNc7gCI/edit?usp=sharing';
export let COMMON_COURTS_POLTAVSKA = 'https://docs.google.com/spreadsheets/d/1UVFAbxlZjtIAl4ClmZmJxLVFg3CNJyYailOLgxHjdbk/edit?usp=sharing';
export let COMMON_COURTS_RIVNENSKA = 'https://docs.google.com/spreadsheets/d/1QIdq6tbas8ReCEwpJKxejQNTIFsH0I5kDlZSPFxV5ic/edit?usp=sharing';
export let COMMON_COURTS_SUMSKA = 'https://docs.google.com/spreadsheets/d/1gSF3qV5zcySgHQapbQfFobEQ1gEkA__InGsLHPKS-d0/edit?usp=sharing';
export let COMMON_COURTS_TERNOPILSKA = 'https://docs.google.com/spreadsheets/d/1Eu44_Q9PJ3ZR0ghrJq-ftW4-QTsIbIgvBsAmWE3DB3s/edit?usp=sharing';
export let COMMON_COURTS_KHARKIVSKA = 'https://docs.google.com/spreadsheets/d/1hVKKSNBo4uY4QHw3vn9RHN9CbH7OyaMxHlMcJoIt1g8/edit?usp=sharing';
export let COMMON_COURTS_KHERSONSKA = 'https://docs.google.com/spreadsheets/d/1CO1VS4CNahwrTFqcGBUrg72oTv2AeCHuxlrTRJYWY20/edit?usp=sharing';
export let COMMON_COURTS_KHMELNITSKA = 'https://docs.google.com/spreadsheets/d/1UXp1-hxXWdvJIGEaAY1PIbRH5DtMYSKvLoY_8Oua8os/edit?usp=sharing';
export let COMMON_COURTS_CHERKASKA = 'https://docs.google.com/spreadsheets/d/1vkYueZH4faueMtPd7IHctZ3J1FIhCbn19so87_hiRYs/edit?usp=sharing';
export let COMMON_COURTS_CHERNIVETSKA = 'https://docs.google.com/spreadsheets/d/1vKpR7HosTjIdSSFFHG67T0bFb5jfNIEU8MmcPMd7Tpo/edit?usp=sharing';
export let COMMON_COURTS_CHERNIGIVSKA = 'https://docs.google.com/spreadsheets/d/1Jpm5bM7CzRkG6gDL2fTpHddj_NSQIerFf3beYDnfCuY/edit?usp=sharing';


export let ADMINISTRATIVE_COURTS = 'https://docs.google.com/spreadsheets/d/1EzhG1OWLbweaHYlJav5fLoH0OscTAKKG/edit?usp=sharing&ouid=105740362998198347900&rtpof=true&sd=true';
export let COMMERCIAL_COURTS = 'https://docs.google.com/spreadsheets/d/1F0GuA6DAnmS2pfjlNRynCHWO1zh57gCk/edit?usp=sharing&ouid=105740362998198347900&rtpof=true&sd=true';
export let APPEAL_COMMON_COURTS ='https://docs.google.com/spreadsheets/d/18bXBqR7DEPxitbnwHWBH98xf9b27ZkG7/edit?usp=sharing&ouid=105740362998198347900&rtpof=true&sd=true';
export let APPEAL_ADMINISTRATIVE_COURTS = 'https://docs.google.com/spreadsheets/d/1veG5N9QmersoUczjxS9NZNnKkETswOUW/edit?usp=sharing&ouid=105740362998198347900&rtpof=true&sd=true';
export let APPEAL_COMMERCIAL_COURTS = 'https://docs.google.com/spreadsheets/d/1qztKzBsAElY8PP37Tnhx2f8KsC4NzGoy/edit?usp=sharing&ouid=105740362998198347900&rtpof=true&sd=true';